function idLoad()
idCreate(2,"gamestate","start")
idCreate(3,"gamestate","options")


idCreate(5,"gamestate","main menu")
idCreate(6,"gamestate","pre1")
idCreate(7,"gamestate","new")
idCreate(8,"gamestate","load")
idCreate(9,"gamestate","arcade")
idCreate(10,"gamestate","multi-player")
idCreate(11,"gamestate","credits")
idCreate(12,"funct","volume",volumeDown)
idCreate(13,"funct","volume",volumeUp)
idCreate(14,"funct","new",previous)
idCreate(15,"funct","new",nextShip)
idCreate(16,'funct','load',deleteSave,rightClicked)
idCreate(17,"funct","multi",previousP1)
idCreate(18,"funct","multi",nextP1)
idCreate(19,"funct","multi",previousP2)
idCreate(20,"funct","multi",nextP2)
idCreate(21,"funct","options",saveOptions)
idCreate(22,"gamestate","mplaying")
idCreate(23,"gamestate","marcade")
idCreate(24,"funct","gamepad",gamepadToggle)
idCreate(27,"funct","pre1",levels.Select,1)
idCreate(28,"funct","pre1",levels.Select,2)
idCreate(29,'funct','win',levels.Next)
idCreate(25,"funct","new",saveGame1)
idCreate(100,"funct","load",loadFromLog,1)
idCreate(200,"funct","load",loadFromLog,2)
idCreate(300,"funct","load",loadFromLog,3)
idCreate(400,"funct","load",loadFromLog,4)
idCreate(500,"funct","load",loadFromLog,5)
idCreate(600,"funct","load",loadFromLog,6)
idCreate(700,"funct","load",loadFromLog,7)
idCreate(800,"funct","load",loadFromLog,8)
idCreate(900,"funct","load",loadFromLog,9)
idCreate(1000,"funct","load",loadFromLog,10)
idCreate(1100,"funct","load",loadFromLog,11)
idCreate(1200,"funct","load",loadFromLog,12)
idCreate(1300,"funct","load",loadFromLog,13)
idCreate(1400,"funct","load",loadFromLog,14)
idCreate(1500,"funct","load",loadFromLog,15)
idCreate(1600,"funct","load",loadFromLog,16)
idCreate(1700,"funct","load",loadFromLog,17)
idCreate(1800,"funct","load",loadFromLog,18)
idCreate(1900,"funct","load",loadFromLog,19)
idCreate(2000,"funct","load",loadFromLog,20)
end


-- button sound credit http://www.freesfx.co.uk



